-- Create page_views table
CREATE TABLE IF NOT EXISTS page_views (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    visitor_token TEXT NOT NULL,
    page_path TEXT DEFAULT '/'
);

-- Enable Row Level Security
ALTER TABLE page_views ENABLE ROW LEVEL SECURITY;

-- Allow anonymous inserts (so public visitors can be logged)
CREATE POLICY "Allow public inserts" ON page_views
    FOR INSERT 
    TO anon
    WITH CHECK (true);

-- Allow authenticated (admin) users to view all data
CREATE POLICY "Allow authenticated view" ON page_views
    FOR SELECT 
    TO authenticated
    USING (true);

-- Create index for faster counting by date
CREATE INDEX IF NOT EXISTS idx_page_views_created_at ON page_views(created_at);
